#!/usr/bin/env bash
#Telling a story I guess.

passwd_file="/etc/passwd"

while IFS=: read -r username password uid gid user_info home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
	echo "USER ID's place is protected by the passcode $password, more info about the user here: $full_name"
	echo
done < "$passwd_file"
