#!/usr/bin/env bash
#Telling a story I guess.

while IFS=: read -r username password uid gid user_info home shell 
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
