#!/usr/bin/env bash
#A script to test loops and ifs
x=1
while [ $x -lt 11 ] && [ $x -gt 0 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo $x
	fi
	((x++))
done
