#!/usr/bin/env bash
#A script to practice whiles and cases
x=1
while [ $x -gt 0 ] && [ $x -le 20 ]
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((x++))
done
