#!/usr/bin/env bash
#pointless loops on top of loops that aren't even accurate to clocks.
x=0
y=1
while [ $x -ge 0 ] && [ $x -le 12 ]
do
	echo "Hour: $x"
	while [ $y -ge 1 ] && [ $y -le 59 ]
	do
		echo "$y"
		((y++))
	done
	((x++))
	y=1
done
