#!/usr/bin/env bash
#This teaches us how to loop through files, tell us if it exists or not,
#and if it's empty and / or a regular file.
#Honestly. I don't know why someone would loop through files like this
#for this specific information
#it's frustrating

file="school"
if [ -e "$file" ]; then
	echo "school file exists"
	if [-s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
